const ACTIONS = {
  // for project
  CREATE_PROJECT: "CREATE_PROJECT",
  CREATE_PROJECT_FAILURE: "CREATE_PROJECT_FAILURE",

  // for authentication
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  // sgning out
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
}

export default ACTIONS
