const ACTIONS={
  // for project
  CREATE_PROJECT :"CREATE_PROJECT",
  CREATE_PROJECT_FAILURE:"CREATE_PROJECT_FAILURE",


  // for authentication
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  LOGIN_FAILURE:"LOGIN_FAILURE"
}

export default ACTIONS